name: smart_lock
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.0.5
  dio: ^5.9.0
  logger: ^2.6.2
  material_symbols_icons: ^4.2874.0
  fpdart: ^1.2.0
  internet_connection_checker_plus: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0


flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#1d4593"
  color_dark: "#1d4593"

  image: assets/logos/logo_white.png
  image_dark: assets/logos/logo_white.png

  android_12:
    color: "#1d4593"
    color_dark: "#1d4593"
    image: assets/logos/logo_white.png
    image_dark: assets/logos/logo_white.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_primary.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/logos/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
